In [130]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(123)

In [131]:
np.random.choice(['a', 'b', 'c', 'd'], (10,3))

array([['c', 'b', 'c'],
       ['c', 'a', 'c'],
       ['c', 'b', 'd'],
       ['c', 'd', 'b'],
       ['c', 'b', 'a'],
       ['b', 'c', 'd'],
       ['b', 'a', 'c'],
       ['a', 'd', 'b'],
       ['d', 'c', 'b'],
       ['a', 'a', 'a']], dtype='<U1')

In [132]:
np.random.uniform(10, 20, (6, 5))

array([[17.37995406, 11.8249173 , 11.75451756, 15.31551374, 15.31827587],
       [16.34400959, 18.49431794, 17.24455325, 16.11023511, 17.22443383],
       [13.22958914, 13.61788656, 12.28263231, 12.93714046, 16.30976124],
       [10.9210494 , 14.33701173, 14.30862763, 14.93685098, 14.2583029 ],
       [13.12261223, 14.26351307, 18.93389163, 19.44160018, 15.01836676],
       [16.23952952, 11.15618395, 13.17285482, 14.14826212, 18.66309158]])

In [133]:
np.random.random([6, 5])

array([[0.25045537, 0.48303426, 0.98555979, 0.51948512, 0.61289453],
       [0.12062867, 0.8263408 , 0.60306013, 0.54506801, 0.34276383],
       [0.30412079, 0.41702221, 0.68130077, 0.87545684, 0.51042234],
       [0.66931378, 0.58593655, 0.6249035 , 0.67468905, 0.84234244],
       [0.08319499, 0.76368284, 0.24366637, 0.19422296, 0.57245696],
       [0.09571252, 0.88532683, 0.62724897, 0.72341636, 0.01612921]])

In [142]:
np.random.randn(6,5)

array([[ 0.81501092,  0.72384338,  0.52808476, -0.49353157,  1.50199665],
       [-0.18825592, -0.74011154, -1.16052868,  0.13152905,  0.37812833],
       [ 0.7281788 ,  1.05483501, -0.14231781, -1.43572138,  0.57670033],
       [ 1.01796463,  0.47004613, -0.16205926, -1.76116099, -0.06750818],
       [-1.1981188 , -0.57795225, -1.40918656, -0.39382191, -0.15077027],
       [ 1.19208584,  0.30390552, -0.15458691,  0.59248135, -0.26846333]])

In [143]:
np.random.normal(10, 3, (6, 5))

array([[ 1.54159491,  7.5569088 , 11.20928544,  9.54766321,  5.43898198],
       [14.09264921,  6.18209967, 11.45479092,  8.70133153,  6.85222867],
       [10.08764156, 13.38712787, 10.6040199 ,  9.72754007,  8.33462115],
       [12.97246208, 15.22280274,  6.94047838,  5.48248591,  8.2435208 ],
       [ 9.39714481,  8.93565562,  7.97455027,  5.43358458, 10.77177234],
       [ 7.55219305,  3.87348654,  5.32972509, 12.82608547,  9.01779062]])

## Carnival Dice Roll

You are at a carnival and come across a person in a booth offering you a game of "chance" (as people in booths at carnivals tend to do).

You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater than 12, you get 15 dollars. If it's less than or equal to 12, you get nothing.

Assuming the dice are fair, should you play this game? How would this change if the winning condition was a sum greater than or equal to 12?

In [144]:
n_dice_rolled = 3
target = 12

In [145]:
def roll_the_dice(ntrials, n_dice_rolled=3, target=12):
    rolls = np.random.choice([1, 2, 3, 4, 5, 6], (ntrials, n_dice_rolled))
    roll_sums = rolls.sum(axis=1)
    roll_wins = sum([1 for roll in roll_sum if roll > target])
    p_win = roll_wins/ntrials
    win_pctg = 100*p_win
    mean_winnings = (15*p_win) - 5
    print(f'Trials: {ntrials:d}')
    print(f'Winning percentage: {win_pctg:.3f}%')
    print(f'Winnings per roll: ${mean_winnings:.2f}')
    return roll_sums

In [146]:
ntrials = 100000

roll_results = roll_the_dice(ntrials, n_dice_rolled, target)

Trials: 100000
Winning percentage: 2.498%
Winnings per roll: $-4.63

## Nappy Time

There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

In [147]:
p_nap = .3
naps = np.random.random((10,2)) <= p_nap

In [148]:
Naps_taken= (naps.sum(axis=1) >= 1).mean()
No_nap = (naps.sum(axis=1) == 0).mean()

## Chance of a 3

In [149]:
def dice_roll(ntrials=10, n_dice=5):
    rolls = pd.DataFrame(np.random.choice([1,2,3,4,5,6], (ntrials, n_dice)))
    rolls['has_3'] = rolls.apply(lambda row: 3 in row.values, axis=1)
    return rolls

In [150]:
ntrials = 100000
n_dice = 5
rolls = dice_roll(ntrials=ntrials, n_dice=n_dice)
p_has_3 = sum(rolls.has_3) / ntrials
print(p_has_3)
pd.DataFrame(rolls)

0.59953

       0  1  2  3  4  has_3
0      4  6  5  5  5  False
1      2  6  5  5  6  False
2      4  6  2  4  6  False
3      1  3  2  2  1   True
4      4  4  4  6  3   True
5      4  2  1  6  3   True
6      4  3  4  1  6   True
7      6  5  6  5  2  False
8      4  4  5  3  6   True
9      5  5  1  6  3   True
10     1  4  2  5  6  False
11     2  2  1  6  2  False
12     6  2  2  3  2   True
13     6  2  2  5  6  False
14     3  5  5  1  6   True
15     5  5  4  6  4  False
16     5  2  4  1  1  False
17     3  2  6  2  6   True
18     1  5  5  5  1  False
19     5  1  1  4  4  False
20     1  1  5  5  4  False
21     6  1  2  5  4  False
22     6  5  4  5  4  False
23     5  1  1  1  3   True
24     6  2  5  1  4  False
25     3  2  6  2  5   True
26     3  3  6  5  4   True
27     3  2  6  5  3   True
28     3  4  4  2  4   True
29     1  1  5  2  3   True
...   .. .. .. .. ..    ...
99970  5  1  5  6  1  False
99971  1  5  3  6  1   True
99972  2  6  5  5  6  False
99973  1  1  3  1  6   True
99974  5  5  1  3  5   True
99975  2  1  5  3  6   True
99976  3  5  1  6  5   True
99977  4  4  4  2  2  False
99978  4  2  5  4  6  False
99979  2  2  2  6  2  False
99980  5  6  5  4  6  False
99981  3  2  6  4  6   True
99982  4  3  1  1  6   True
99983  2  6  5  3  4   True
99984  1  3  2  4  2   True
99985  4  4  6  4  5  False
99986  5  5  6  2  6  False
99987  1  6  5  2  6  False
99988  6  6  6  4  5  False
99989  1  1  4  5  3   True
99990  5  5  2  5  3   True
99991  6  6  2  1  6  False
99992  4  1  2  5  1  False
99993  4  5  6  6  4  False
99994  3  6  4  6  4   True
99995  5  6  2  3  2   True
99996  4  2  4  3  1   True
99997  5  4  3  2  1   True
99998  5  3  4  3  2   True
99999  6  4  3  1  5   True

[100000 rows x 6 columns]

In [151]:
np.random.seed()